const breakfast =[
    {"id":"7",
    "name": "Bagel and cream cheese",
    "shortDescription": "How we dream about our future",
    "price": 6.99,
    "details": "Gay one the what walk then she. Demsene mention promise you justice arrived way. Amaizing foods are  or and increasing to in especially inquietude companions acceeptance admiration. Out weight it families distance wandered yet",
    "photo": "https://iili.io/2TC10g.md.png",
    "category": "breakfast"
    },
    {"id": "8",
    "name": "Breakfast sandwich",
    "shortDescription": "How we dream about our future",
    "price": 9.99,
    "details": "Gay one the what walk then she. Demsene mention promise you justice arrived way. Amaizing foods are  or and increasing to in especially inquietude companions acceeptance admiration. Out weight it families distance wandered yet",
    "photo": "https://iili.io/2TCEga.md.png",
    "category": "breakfast"
    },
    {"id": "9",
    "name": "Backed Chicken",
    "shortDescription": "How we dream about our future",
    "price": 10.99,
    "details": "Gay one the what walk then she. Demsene mention promise you justice arrived way. Amaizing foods are  or and increasing to in especially inquietude companions acceeptance admiration. Out weight it families distance wandered yet",
    "photo": "https://iili.io/2TCMdJ.md.png",
    "category": "breakfast"
    },
    {"id": "10",
    "name": "Eggs Benedict",
    "shortDescription": "How we dream about our future",
    "price": 8.99,
    "details": "At Bamboo Inn, we offer Free prawn crackers with food order over £18. FREE mini vegetable spring rolls with food order over night.",
    "photo": "https://iili.io/2TCV5v.md.png",
    "category": "breakfast"
    },
    {"id":"11",
    "name": "Toast Croissant Fried Egg",
    "shortDescription": "How we dream about our future",
    "price": 19.99,
    "details": "Gay one the what walk then she. Demsene mention promise you justice arrived way. Amaizing foods are  or and increasing to in especially inquietude companions acceeptance admiration. Out weight it families distance wandered yet",
    "photo": "https://iili.io/2TCWeR.md.png",
    "category": "breakfast"
    },
    {"id": "12",
    "name": "Full breakfasrt Fried Egg Toast Brunch",
    "shortDescription": "How we dream about our future",
    "price": 3.99,
    "details": "Gay one the what walk then she. Demsene mention promise you justice arrived way. Amaizing foods are  or and increasing to in especially inquietude companions acceeptance admiration. Out weight it families distance wandered yet",
    "photo": "https://iili.io/2TCXbp.md.png",
    "category": "breakfast"
    },
    ]
    export default breakfast;